// Algerian wilayas with bilingual data for programmatic SEO
export interface Wilaya {
  code: number;
  slug: string;
  name: { fr: string; ar: string };
  region: { fr: string; ar: string };
  population?: number;
  lat: number;
  lng: number;
  // SEO-tailored short pitch (sectors/economy)
  pitch: { fr: string; ar: string };
}

export const WILAYAS: Wilaya[] = [
  { code: 1, slug: 'adrar', name: { fr: 'Adrar', ar: 'أدرار' }, region: { fr: 'Sud-Ouest', ar: 'الجنوب الغربي' }, population: 439700, lat: 27.8742, lng: -0.2939, pitch: { fr: 'Distribution longue distance, transport routier et agriculture saharienne.', ar: 'التوزيع لمسافات طويلة، النقل البري والزراعة الصحراوية.' } },
  { code: 2, slug: 'chlef', name: { fr: 'Chlef', ar: 'الشلف' }, region: { fr: 'Nord-Ouest', ar: 'الشمال الغربي' }, population: 1078000, lat: 36.1700, lng: 1.3340, pitch: { fr: 'Pôle agricole, agroalimentaire et matériaux de construction.', ar: 'قطب زراعي، صناعات غذائية ومواد بناء.' } },
  { code: 3, slug: 'laghouat', name: { fr: 'Laghouat', ar: 'الأغواط' }, region: { fr: 'Hauts Plateaux', ar: 'الهضاب العليا' }, population: 480000, lat: 33.8000, lng: 2.8650, pitch: { fr: 'Distribution alimentaire et services pétroliers.', ar: 'توزيع المواد الغذائية وخدمات النفط.' } },
  { code: 4, slug: 'oum-el-bouaghi', name: { fr: 'Oum El Bouaghi', ar: 'أم البواقي' }, region: { fr: 'Est', ar: 'الشرق' }, population: 644000, lat: 35.8762, lng: 7.1131, pitch: { fr: 'Élevage, céréales et distribution rurale.', ar: 'تربية الماشية، الحبوب والتوزيع الريفي.' } },
  { code: 5, slug: 'batna', name: { fr: 'Batna', ar: 'باتنة' }, region: { fr: 'Aurès', ar: 'الأوراس' }, population: 1119000, lat: 35.5559, lng: 6.1741, pitch: { fr: 'Industrie, textile et distribution alimentaire.', ar: 'الصناعة، النسيج وتوزيع الأغذية.' } },
  { code: 6, slug: 'bejaia', name: { fr: 'Béjaïa', ar: 'بجاية' }, region: { fr: 'Kabylie', ar: 'القبائل' }, population: 915000, lat: 36.7515, lng: 5.0567, pitch: { fr: 'Port commercial, agroalimentaire (Cevital), distribution moderne.', ar: 'ميناء تجاري، صناعات غذائية (سيفيتال) وتوزيع حديث.' } },
  { code: 7, slug: 'biskra', name: { fr: 'Biskra', ar: 'بسكرة' }, region: { fr: 'Sahara Nord', ar: 'الشمال الصحراوي' }, population: 730000, lat: 34.8500, lng: 5.7333, pitch: { fr: 'Capitale des dattes, agroalimentaire et distribution régionale.', ar: 'عاصمة التمور، الصناعات الغذائية والتوزيع الإقليمي.' } },
  { code: 8, slug: 'bechar', name: { fr: 'Béchar', ar: 'بشار' }, region: { fr: 'Sud-Ouest', ar: 'الجنوب الغربي' }, population: 290000, lat: 31.6177, lng: -2.2167, pitch: { fr: 'Logistique, mines et distribution sahariennes.', ar: 'لوجستيات، مناجم وتوزيع صحراوي.' } },
  { code: 9, slug: 'blida', name: { fr: 'Blida', ar: 'البليدة' }, region: { fr: 'Mitidja', ar: 'متيجة' }, population: 1100000, lat: 36.4720, lng: 2.8277, pitch: { fr: 'Pôle industriel et agricole, hub logistique d\'Alger.', ar: 'قطب صناعي وزراعي، مركز لوجستي للعاصمة.' } },
  { code: 10, slug: 'bouira', name: { fr: 'Bouira', ar: 'البويرة' }, region: { fr: 'Centre', ar: 'الوسط' }, population: 720000, lat: 36.3737, lng: 3.9020, pitch: { fr: 'Agroalimentaire, BTP et distribution régionale.', ar: 'صناعات غذائية، البناء والتوزيع الإقليمي.' } },
  { code: 11, slug: 'tamanrasset', name: { fr: 'Tamanrasset', ar: 'تمنراست' }, region: { fr: 'Grand Sud', ar: 'الجنوب الكبير' }, population: 200000, lat: 22.7850, lng: 5.5228, pitch: { fr: 'Logistique transsaharienne et tourisme.', ar: 'لوجستيات عبر الصحراء والسياحة.' } },
  { code: 12, slug: 'tebessa', name: { fr: 'Tébessa', ar: 'تبسة' }, region: { fr: 'Est', ar: 'الشرق' }, population: 700000, lat: 35.4044, lng: 8.1242, pitch: { fr: 'Mines (phosphates), commerce frontalier et distribution.', ar: 'مناجم (فوسفات)، تجارة حدودية وتوزيع.' } },
  { code: 13, slug: 'tlemcen', name: { fr: 'Tlemcen', ar: 'تلمسان' }, region: { fr: 'Ouest', ar: 'الغرب' }, population: 950000, lat: 34.8826, lng: -1.3167, pitch: { fr: 'Textile, agroalimentaire, commerce frontalier.', ar: 'النسيج، الصناعات الغذائية والتجارة الحدودية.' } },
  { code: 14, slug: 'tiaret', name: { fr: 'Tiaret', ar: 'تيارت' }, region: { fr: 'Hauts Plateaux Ouest', ar: 'الهضاب الغربية' }, population: 890000, lat: 35.3700, lng: 1.3170, pitch: { fr: 'Céréales, élevage, distribution alimentaire.', ar: 'الحبوب، تربية الماشية وتوزيع الأغذية.' } },
  { code: 15, slug: 'tizi-ouzou', name: { fr: 'Tizi Ouzou', ar: 'تيزي وزو' }, region: { fr: 'Kabylie', ar: 'القبائل' }, population: 1130000, lat: 36.7169, lng: 4.0497, pitch: { fr: 'Commerce dynamique, électronique et agroalimentaire.', ar: 'تجارة نشطة، إلكترونيات وصناعات غذائية.' } },
  { code: 16, slug: 'alger', name: { fr: 'Alger', ar: 'الجزائر' }, region: { fr: 'Capitale', ar: 'العاصمة' }, population: 3500000, lat: 36.7538, lng: 3.0588, pitch: { fr: 'Capitale économique : siège des plus grands distributeurs et grossistes d\'Algérie.', ar: 'العاصمة الاقتصادية: مقر أكبر الموزعين وتجار الجملة في الجزائر.' } },
  { code: 17, slug: 'djelfa', name: { fr: 'Djelfa', ar: 'الجلفة' }, region: { fr: 'Hauts Plateaux', ar: 'الهضاب العليا' }, population: 1450000, lat: 34.6700, lng: 3.2630, pitch: { fr: 'Élevage ovin, marché à bétail le plus grand d\'Algérie.', ar: 'تربية الأغنام، أكبر سوق للماشية في الجزائر.' } },
  { code: 18, slug: 'jijel', name: { fr: 'Jijel', ar: 'جيجل' }, region: { fr: 'Nord-Est', ar: 'الشمال الشرقي' }, population: 700000, lat: 36.8190, lng: 5.7660, pitch: { fr: 'Port, sidérurgie et distribution côtière.', ar: 'ميناء، صناعة الحديد والتوزيع الساحلي.' } },
  { code: 19, slug: 'setif', name: { fr: 'Sétif', ar: 'سطيف' }, region: { fr: 'Hauts Plateaux Est', ar: 'الهضاب الشرقية' }, population: 1700000, lat: 36.1900, lng: 5.4100, pitch: { fr: 'Capitale industrielle de l\'Est : agroalimentaire, électroménager, distribution.', ar: 'العاصمة الصناعية للشرق: صناعات غذائية، أجهزة منزلية وتوزيع.' } },
  { code: 20, slug: 'saida', name: { fr: 'Saïda', ar: 'سعيدة' }, region: { fr: 'Ouest', ar: 'الغرب' }, population: 360000, lat: 34.8400, lng: 0.1500, pitch: { fr: 'Eaux minérales, agroalimentaire et distribution.', ar: 'المياه المعدنية، الصناعات الغذائية والتوزيع.' } },
  { code: 21, slug: 'skikda', name: { fr: 'Skikda', ar: 'سكيكدة' }, region: { fr: 'Nord-Est', ar: 'الشمال الشرقي' }, population: 950000, lat: 36.8761, lng: 6.9094, pitch: { fr: 'Pétrochimie, port et distribution industrielle.', ar: 'البتروكيمياء، الميناء والتوزيع الصناعي.' } },
  { code: 22, slug: 'sidi-bel-abbes', name: { fr: 'Sidi Bel Abbès', ar: 'سيدي بلعباس' }, region: { fr: 'Ouest', ar: 'الغرب' }, population: 650000, lat: 35.1900, lng: -0.6300, pitch: { fr: 'Électronique, agroalimentaire et distribution.', ar: 'الإلكترونيات، الصناعات الغذائية والتوزيع.' } },
  { code: 23, slug: 'annaba', name: { fr: 'Annaba', ar: 'عنابة' }, region: { fr: 'Est', ar: 'الشرق' }, population: 640000, lat: 36.9000, lng: 7.7667, pitch: { fr: 'Sidérurgie (El Hadjar), port et grand commerce.', ar: 'صناعة الحديد (الحجار)، الميناء والتجارة الكبرى.' } },
  { code: 24, slug: 'guelma', name: { fr: 'Guelma', ar: 'قالمة' }, region: { fr: 'Est', ar: 'الشرق' }, population: 530000, lat: 36.4622, lng: 7.4258, pitch: { fr: 'Agroalimentaire et distribution régionale.', ar: 'الصناعات الغذائية والتوزيع الإقليمي.' } },
  { code: 25, slug: 'constantine', name: { fr: 'Constantine', ar: 'قسنطينة' }, region: { fr: 'Est', ar: 'الشرق' }, population: 950000, lat: 36.3650, lng: 6.6147, pitch: { fr: 'Capitale de l\'Est, industrie pharmaceutique et grand commerce.', ar: 'عاصمة الشرق، صناعة الأدوية والتجارة الكبرى.' } },
  { code: 26, slug: 'medea', name: { fr: 'Médéa', ar: 'المدية' }, region: { fr: 'Centre', ar: 'الوسط' }, population: 850000, lat: 36.2640, lng: 2.7536, pitch: { fr: 'Agriculture, viticulture et distribution.', ar: 'الزراعة، تربية الكروم والتوزيع.' } },
  { code: 27, slug: 'mostaganem', name: { fr: 'Mostaganem', ar: 'مستغانم' }, region: { fr: 'Ouest', ar: 'الغرب' }, population: 770000, lat: 35.9333, lng: 0.0833, pitch: { fr: 'Port de pêche, agroalimentaire et distribution.', ar: 'ميناء صيد، الصناعات الغذائية والتوزيع.' } },
  { code: 28, slug: 'msila', name: { fr: 'M\'Sila', ar: 'المسيلة' }, region: { fr: 'Hauts Plateaux', ar: 'الهضاب العليا' }, population: 1020000, lat: 35.7000, lng: 4.5400, pitch: { fr: 'Cimenterie, élevage et distribution.', ar: 'الإسمنت، تربية الماشية والتوزيع.' } },
  { code: 29, slug: 'mascara', name: { fr: 'Mascara', ar: 'معسكر' }, region: { fr: 'Ouest', ar: 'الغرب' }, population: 800000, lat: 35.4000, lng: 0.1400, pitch: { fr: 'Viticulture, agroalimentaire et distribution.', ar: 'تربية الكروم، الصناعات الغذائية والتوزيع.' } },
  { code: 30, slug: 'ouargla', name: { fr: 'Ouargla', ar: 'ورقلة' }, region: { fr: 'Sahara', ar: 'الصحراء' }, population: 560000, lat: 31.9500, lng: 5.3300, pitch: { fr: 'Capitale pétrolière du Sud, services industriels et distribution.', ar: 'عاصمة النفط في الجنوب، الخدمات الصناعية والتوزيع.' } },
  { code: 31, slug: 'oran', name: { fr: 'Oran', ar: 'وهران' }, region: { fr: 'Ouest', ar: 'الغرب' }, population: 1700000, lat: 35.6987, lng: -0.6349, pitch: { fr: 'Capitale économique de l\'Ouest, port et grands distributeurs.', ar: 'العاصمة الاقتصادية للغرب، ميناء وكبار الموزعين.' } },
  { code: 32, slug: 'el-bayadh', name: { fr: 'El Bayadh', ar: 'البيض' }, region: { fr: 'Sud-Ouest', ar: 'الجنوب الغربي' }, population: 270000, lat: 33.6800, lng: 1.0200, pitch: { fr: 'Élevage et distribution rurale.', ar: 'تربية الماشية والتوزيع الريفي.' } },
  { code: 33, slug: 'illizi', name: { fr: 'Illizi', ar: 'إليزي' }, region: { fr: 'Grand Sud-Est', ar: 'الجنوب الشرقي' }, population: 80000, lat: 26.5000, lng: 8.4667, pitch: { fr: 'Hydrocarbures et logistique saharienne.', ar: 'المحروقات واللوجستيات الصحراوية.' } },
  { code: 34, slug: 'bordj-bou-arreridj', name: { fr: 'Bordj Bou Arréridj', ar: 'برج بوعريريج' }, region: { fr: 'Hauts Plateaux Est', ar: 'الهضاب الشرقية' }, population: 740000, lat: 36.0731, lng: 4.7611, pitch: { fr: 'Capitale de l\'électronique algérienne, grands distributeurs.', ar: 'عاصمة الإلكترونيات الجزائرية، كبار الموزعين.' } },
  { code: 35, slug: 'boumerdes', name: { fr: 'Boumerdès', ar: 'بومرداس' }, region: { fr: 'Centre', ar: 'الوسط' }, population: 880000, lat: 36.7600, lng: 3.4800, pitch: { fr: 'Agriculture, pétrochimie et distribution côtière.', ar: 'الزراعة، البتروكيمياء والتوزيع الساحلي.' } },
  { code: 36, slug: 'el-tarf', name: { fr: 'El Tarf', ar: 'الطارف' }, region: { fr: 'Nord-Est', ar: 'الشمال الشرقي' }, population: 450000, lat: 36.7672, lng: 8.3133, pitch: { fr: 'Pêche, agriculture et commerce frontalier.', ar: 'الصيد، الزراعة والتجارة الحدودية.' } },
  { code: 37, slug: 'tindouf', name: { fr: 'Tindouf', ar: 'تندوف' }, region: { fr: 'Extrême Sud-Ouest', ar: 'أقصى الجنوب الغربي' }, population: 60000, lat: 27.6700, lng: -8.1500, pitch: { fr: 'Mines de fer et logistique.', ar: 'مناجم الحديد واللوجستيات.' } },
  { code: 38, slug: 'tissemsilt', name: { fr: 'Tissemsilt', ar: 'تيسمسيلت' }, region: { fr: 'Hauts Plateaux Ouest', ar: 'الهضاب الغربية' }, population: 320000, lat: 35.6000, lng: 1.8100, pitch: { fr: 'Agriculture et distribution rurale.', ar: 'الزراعة والتوزيع الريفي.' } },
  { code: 39, slug: 'el-oued', name: { fr: 'El Oued', ar: 'الوادي' }, region: { fr: 'Sahara Nord', ar: 'الشمال الصحراوي' }, population: 750000, lat: 33.3683, lng: 6.8675, pitch: { fr: 'Dattes, pomme de terre et grand commerce frontalier.', ar: 'التمور، البطاطا والتجارة الحدودية الكبرى.' } },
  { code: 40, slug: 'khenchela', name: { fr: 'Khenchela', ar: 'خنشلة' }, region: { fr: 'Aurès', ar: 'الأوراس' }, population: 410000, lat: 35.4350, lng: 7.1430, pitch: { fr: 'Agriculture de montagne et distribution.', ar: 'الزراعة الجبلية والتوزيع.' } },
  { code: 41, slug: 'souk-ahras', name: { fr: 'Souk Ahras', ar: 'سوق أهراس' }, region: { fr: 'Est', ar: 'الشرق' }, population: 470000, lat: 36.2860, lng: 7.9510, pitch: { fr: 'Commerce frontalier (Tunisie) et agroalimentaire.', ar: 'التجارة الحدودية (تونس) والصناعات الغذائية.' } },
  { code: 42, slug: 'tipaza', name: { fr: 'Tipaza', ar: 'تيبازة' }, region: { fr: 'Centre', ar: 'الوسط' }, population: 620000, lat: 36.5944, lng: 2.4475, pitch: { fr: 'Tourisme, agriculture et distribution moderne.', ar: 'السياحة، الزراعة والتوزيع الحديث.' } },
  { code: 43, slug: 'mila', name: { fr: 'Mila', ar: 'ميلة' }, region: { fr: 'Est', ar: 'الشرق' }, population: 800000, lat: 36.4500, lng: 6.2670, pitch: { fr: 'Agriculture, agroalimentaire et distribution régionale.', ar: 'الزراعة، الصناعات الغذائية والتوزيع الإقليمي.' } },
  { code: 44, slug: 'ain-defla', name: { fr: 'Aïn Defla', ar: 'عين الدفلى' }, region: { fr: 'Centre-Ouest', ar: 'الوسط الغربي' }, population: 770000, lat: 36.2600, lng: 1.9700, pitch: { fr: 'Agriculture, agroalimentaire et distribution.', ar: 'الزراعة، الصناعات الغذائية والتوزيع.' } },
  { code: 45, slug: 'naama', name: { fr: 'Naâma', ar: 'النعامة' }, region: { fr: 'Sud-Ouest', ar: 'الجنوب الغربي' }, population: 200000, lat: 33.2667, lng: -0.3167, pitch: { fr: 'Élevage et logistique frontalière.', ar: 'تربية الماشية واللوجستيات الحدودية.' } },
  { code: 46, slug: 'ain-temouchent', name: { fr: 'Aïn Témouchent', ar: 'عين تموشنت' }, region: { fr: 'Ouest', ar: 'الغرب' }, population: 380000, lat: 35.3000, lng: -1.1400, pitch: { fr: 'Port de Béni Saf, agroalimentaire et distribution.', ar: 'ميناء بني صاف، الصناعات الغذائية والتوزيع.' } },
  { code: 47, slug: 'ghardaia', name: { fr: 'Ghardaïa', ar: 'غرداية' }, region: { fr: 'Sahara', ar: 'الصحراء' }, population: 450000, lat: 32.4900, lng: 3.6700, pitch: { fr: 'Commerce mozabite, textile et distribution saharienne.', ar: 'التجارة المزابية، النسيج والتوزيع الصحراوي.' } },
  { code: 48, slug: 'relizane', name: { fr: 'Relizane', ar: 'غليزان' }, region: { fr: 'Ouest', ar: 'الغرب' }, population: 730000, lat: 35.7370, lng: 0.5560, pitch: { fr: 'Agriculture, textile et distribution.', ar: 'الزراعة، النسيج والتوزيع.' } },
  { code: 49, slug: 'el-mghair', name: { fr: 'El M\'Ghair', ar: 'المغير' }, region: { fr: 'Sahara Nord', ar: 'الشمال الصحراوي' }, population: 175000, lat: 33.9500, lng: 5.9167, pitch: { fr: 'Dattes et distribution agricole.', ar: 'التمور والتوزيع الزراعي.' } },
  { code: 50, slug: 'el-meniaa', name: { fr: 'El Meniaa', ar: 'المنيعة' }, region: { fr: 'Sahara', ar: 'الصحراء' }, population: 60000, lat: 30.5833, lng: 2.8833, pitch: { fr: 'Agriculture saharienne et distribution.', ar: 'الزراعة الصحراوية والتوزيع.' } },
  { code: 51, slug: 'ouled-djellal', name: { fr: 'Ouled Djellal', ar: 'أولاد جلال' }, region: { fr: 'Sahara Nord', ar: 'الشمال الصحراوي' }, population: 175000, lat: 34.4319, lng: 5.0686, pitch: { fr: 'Agriculture et distribution rurale.', ar: 'الزراعة والتوزيع الريفي.' } },
  { code: 52, slug: 'bordj-badji-mokhtar', name: { fr: 'Bordj Badji Mokhtar', ar: 'برج باجي مختار' }, region: { fr: 'Extrême Sud', ar: 'أقصى الجنوب' }, population: 18000, lat: 21.3270, lng: 0.9540, pitch: { fr: 'Commerce transsaharien.', ar: 'التجارة العابرة للصحراء.' } },
  { code: 53, slug: 'beni-abbes', name: { fr: 'Béni Abbès', ar: 'بني عباس' }, region: { fr: 'Sud-Ouest', ar: 'الجنوب الغربي' }, population: 50000, lat: 30.1300, lng: -2.1700, pitch: { fr: 'Tourisme et logistique saharienne.', ar: 'السياحة واللوجستيات الصحراوية.' } },
  { code: 54, slug: 'timimoun', name: { fr: 'Timimoun', ar: 'تيميمون' }, region: { fr: 'Sahara', ar: 'الصحراء' }, population: 130000, lat: 29.2630, lng: 0.2410, pitch: { fr: 'Tourisme saharien et agriculture oasienne.', ar: 'السياحة الصحراوية والزراعة الواحاتية.' } },
  { code: 55, slug: 'touggourt', name: { fr: 'Touggourt', ar: 'تقرت' }, region: { fr: 'Sahara Nord', ar: 'الشمال الصحراوي' }, population: 250000, lat: 33.1000, lng: 6.0667, pitch: { fr: 'Pétrole, dattes et distribution.', ar: 'النفط، التمور والتوزيع.' } },
  { code: 56, slug: 'djanet', name: { fr: 'Djanet', ar: 'جانت' }, region: { fr: 'Extrême Sud-Est', ar: 'أقصى الجنوب الشرقي' }, population: 17000, lat: 24.5500, lng: 9.4833, pitch: { fr: 'Tourisme du Tassili et logistique.', ar: 'سياحة الطاسيلي واللوجستيات.' } },
  { code: 57, slug: 'in-salah', name: { fr: 'In Salah', ar: 'عين صالح' }, region: { fr: 'Sahara', ar: 'الصحراء' }, population: 50000, lat: 27.1980, lng: 2.4660, pitch: { fr: 'Hydrocarbures et logistique saharienne.', ar: 'المحروقات واللوجستيات الصحراوية.' } },
  { code: 58, slug: 'in-guezzam', name: { fr: 'In Guezzam', ar: 'عين قزام' }, region: { fr: 'Frontière Niger', ar: 'الحدود مع النيجر' }, population: 11000, lat: 19.5680, lng: 5.7720, pitch: { fr: 'Commerce frontalier sub-saharien.', ar: 'التجارة الحدودية مع الصحراء الكبرى.' } },
];

export function getWilaya(slug: string): Wilaya | undefined {
  return WILAYAS.find((w) => w.slug === slug);
}
